version: '3'

services:
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: usermanagement
    ports:
      - "5432:5432"
    volumes:
      - ../database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  app:
    build:
      context: ../
      dockerfile: ./dev-env/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=usermanagement;Username=admin;Password=password
    ports:
      - "8000:80"